openapi: '3.0.0'
info:
  title: 'NFT Minting API'
  version: '1.0.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /nft:
    get:
      security:
        - bearerAuth: []
      summary: Get all Minted NFTs.
      responses:
        '200':
          description: The minted NFTs.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                    name:
                      type: string
                    description:
                      type: string
                    imageUrl:
                      type: string
                    owner:
                      type: string
                    transactionHash:
                      type: string
                    tokenURI:
                      type: string
                    tokenId:
                      type: string
                    __v:
                      type: integer
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string 
  /nft/details/{id}:
    get:
      security:
        - bearerAuth: []
      summary: Get NFT Details
      description: Fetch details of a specific NFT by its ID.
      parameters:
        - name: id
          in: path
          description: ID of the NFT to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Get NFT metadata
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  description:
                    type: string
                  imageUrl:
                    type: string
        '400':
          description: Missing required fields
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string 
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string 
        '404':
          description: NFT not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /nft/mint:
    post:
      security:
        - bearerAuth: []
      summary: Mint a new NFT.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - description
                - imageUrl
              properties:
                name:
                  type: string
                description:
                  type: string
                imageUrl:
                  type: string
      responses:
        '201':
          description: Minted NFT
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  name:
                    type: string
                  description:
                    type: string
                  imageUrl:
                    type: string
                  owner:
                    type: string
                  transactionHash:
                    type: string
                  tokenURI:
                    type: string
                  tokenId:
                    type: string
                  __v:
                    type: integer
        '400':
          description: Missing required fields
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string 
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string 
  /auth/login:
    post:
      summary: Log in a user and get a JWT token to use for authenticating the nft paths
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Missing required fields
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '401':
          description: Invalid Credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string           
        '500':
          description: Error logging in
  /auth/register:
    post:
      summary: Registers a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
                - ethAddress
              properties:
                username:
                  type: string
                password:
                  type: string
                ethAddress:
                  type: string
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Missing required fields
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '403':
          description: User already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string           
        '500':
          description: Error logging in
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
